name: azure
on:
  push:
    branches:
      - devlopment
      - main

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Version
        run: |
          echo "{\"lastUpdate\": $(date "+%s")}" > ./project/release-date.json
          git config user.name ${{ secrets.NAME }}
          git config user.email ${{ secrets.EMAIL }}
          git commit -a -m "lastUpdate [skip ci]"
          git push

      - name: Changelog and tags
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          yarn release "-m \"changelog [skip ci]\""
          git push --follow-tags origin master
