name: Release
on: 
  pull_request:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          git fetch origin
          git checkout -b gh-pages --track origin/gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "{\"lastUpdate\": $(date "+%s")}" > release-date.json
          npm run release "-m \"changelog [skip ci]\""
          git push --follow-tags origin main
