name: azure
on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Version
        run: |
          echo "{\"lastUpdate\": $(date "+%s")}" > release-date.json
          git config user.name ${{ secrets.NAME }}
          git config user.email ${{ secrets.EMAIL }}
          git commit -a -m "lastUpdate [skip ci]"
          git push
